testing/core/urls.py
from django.urls import include, path , re_path , include
from . import views


app_name = 'core'
urlpatterns = [
    # path('', views.ListProducts.as_view(), name='product_list'),
    path('', views.ListProducts.as_view(), name='product_list'),
    path('cart/add/<int:id>', views.AddToCartView.as_view(), name='cart_add'),
    path('cart/remove/<int:id>', views.RemoveFromCartView.as_view(), name='cart_remove'),
    path('cart/empty', views.EmptyCartView.as_view(), name='cart_empty'),
    path('cart', views.ShowCartView.as_view(), name='cart_show'),
    path('checkout', views.CheckOutView.as_view(), name='checkout'),
    path('checkout', views.CheckOutView.as_view(), name='checkout'),
    path('verify' , views.VerifyView.as_view(), name='verify'),

    # path('ajaxtestpage', views.AjaxTestPage.as_view()),
    # path('testjson', views.Test.as_view())


]

testing/testing/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('django.contrib.auth.urls')),
    path('account/', include('account.urls', namespace='account')),
    path('', include('core.urls', namespace='core')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

testing/core/models.py
from django.db import models
from uuid import uuid4

from telegram import Invoice

# from django.contrib.auth.models import User
from account.models import User
from django.contrib.auth import get_user_model

# Create your models here.

User = get_user_model()

class Base(models.Model):
    uuid          = models.UUIDField      (unique=True,default=uuid4)
    create_date   = models.DateTimeField  (auto_now_add=True) # auto_now_add  یعنی به محض سیو اولیه ست میشه 
    modified_date = models.DateTimeField  (auto_now=True) 
    delete_date   = models.DateTimeField  (default=None, null=True , blank=True)
    deleted       = models.BooleanField   (default=False)
    user          = models.ForeignKey     (User ,default = 1 ,on_delete=models.PROTECT)

    class Meta:
        abstract = True


class Product(Base):
    
    #Static Attribute
    # STATUS_ENABLED  =  'enabled'
    # STATUS_DISABLED =  'disabled'
    # STATUS_DELETED  =  'deleted' 
    
    # STATUS_CHOICES = (
    #     (STATUS_ENABLED ,'Enabled' ),
    #     (STATUS_DISABLED,'Disabled'),
    #     (STATUS_DELETED ,'Deleted' )

    name          = models.CharField      (max_length=255)
    slug          = models.SlugField      (unique=True)
    price         = models.IntegerField   (default=0)
    discount      = models.FloatField     (default=0)
    enabled       = models.BooleanField   (default=True)
    description   = models.TextField      ()
    category      = models.ForeignKey     ("Category", related_name="products" , on_delete=models.PROTECT)
    image         = models.ImageField     (upload_to="covers/" ,null=True , blank=True)
    button        = models.BooleanField   (default=False)
    count         = models.IntegerField   (default=0)
    # old_category  = models.ForeignKey     ("Category", related_name="old_products" , on_delete=models.PROTECT)

    def __str__(self):
        return f"{self.name}"


class Tag(Base):
    name          = models.CharField      (max_length=255)
    def __str__(self):
        return f"{self.name}"


class Comment(Base):
    name          = models.CharField      (max_length=255)
    def __str__(self):
        return f"{self.name}"

class Like(Base):
    pass
    def __str__(self):
        return f"{self.name}"


class Category(Base):
    name          = models.CharField      (max_length=255)
    parent        = models.ForeignKey     ('Category',null=True ,default=None, blank=True, on_delete=models.PROTECT, related_name='childs')

    def __str__(self):
        return f"{self.name}"




class InvoiceItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    invoice = models.ForeignKey('Invoice', on_delete=models.CASCADE)
    count = models.IntegerField ()
    price = models.IntegerField ()
    discount = models.FloatField ()
    name = models.CharField (max_length=255)
    total = models.IntegerField ()


class Invoice(models.Model):
    date = models.DateTimeField(auto_now_add=True)
    number = models.IntegerField(null = True , blank=True)
    user = models.ForeignKey(User,on_delete=models.PROTECT)
    total = models.IntegerField()
    discount = models.IntegerField(default = 0)
    description = models.TextField(null = True , blank=True)
    address = models.CharField(max_length=255)
    vat = models.FloatField(default = 0.09)

    def __str__(self):
        return f"{self.number}"



class Payment(models.Model):
    STATUS_PENDING = 'Pending'
    STATUS_DONE = 'Done'
    STATUS_ERROR = 'Error'
    STATUS_CHOICES = ((STATUS_PENDING, 'Pending'),
                      (STATUS_DONE, 'Done'),
                      (STATUS_ERROR, 'Error'))


    invoice = models.OneToOneField(Invoice , on_delete=models.PROTECT)
    total = models.IntegerField()
    ref = models.CharField (max_length=255 , null=True , blank=True)
    status = models.CharField (choices = STATUS_CHOICES , max_length=20, default = STATUS_PENDING)

    authority = models.CharField(max_length=255)
    description = models.TextField()
    user_ip = models.CharField(max_length=255)

testing/core/forms.py
from django import forms
from . import models


class InvoiceForm(forms.ModelForm):
    class Meta:
        model = models.Invoice
        fields = ['address']

testing/core/views.py
from django.shortcuts import render , get_object_or_404
from django.views import View
from . import models
# Create your views here.
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import redirect

from django.http import JsonResponse

from . import forms
from zeep import Client

zarinpal = Client('https://zarinpal.com/pg/services/WebGate/wsdl')
mid = 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX'


def get_cart_total_price(cart):
    total = 0

    objects = models.Product.objects.filter(id__in=[int(k) for k in cart.keys()])

    for id , count in cart.items():
        obj = objects.get(id=int(id))
        total +=  (obj.price - obj.price * obj.discount) * count
    return total



def normalize_cart_keys(cart):
    return {str(k): v for k, v in cart.items()}



def get_cart(request):
    cart = request.session.get('cart', {})
    if not isinstance(cart, dict):
        cart = {}
    return normalize_cart_keys(cart)




def remove_from_cart(cart , id):
    id = str(id)
    if id in cart:
        del cart[id]



def add_to_cart(cart , obj):
    if obj.count > 0 and obj.enabled:
        cart[str(obj.id)] = cart.get(str(obj.id), 0) + 1



class ListProducts(View):
    def get(self, request):
        obj =  models.Product.objects.all()
        return render(request, 'core/product_list.html', {'products': obj})


class Button(View):
    def get (self, request):
        obj = models.Button.objects.all()


class AddToCartView(View):
    def get(self, request , id):

            obj = get_object_or_404(models.Product, id=id)
            cart = get_cart(request)
            add_to_cart(cart, obj)
            request.session['cart'] = cart

            if request.headers.get("x-requested-with") == 'XMLHttpRequest':
                #Serialization
                return JsonResponse(cart)
            return HttpResponseRedirect(reverse('core:product_list'))


class RemoveFromCartView(View):
    def get(self , request , id):
        cart =  get_cart(request)
        remove_from_cart(cart , id)
        request.session['cart'] = cart
        if request.headers.get("x-requested-with") == 'XMLHttpRequest':
            # Serialization
            return JsonResponse({'total': get_cart_total_price(cart),
                                 'cart':cart})
        return HttpResponseRedirect(reverse('core:product_list'))


class EmptyCartView(View):
    def get(self , request):
        request.session['cart'] = {}
        if request.headers.get("x-requested-with") == 'XMLHttpRequest':
            # Serialization
            return JsonResponse({'total':0 , 'cart':{} })
        return HttpResponseRedirect(reverse('core:product_list'))


class ShowCartView(View):
    def get(self, request):
        cart = get_cart(request)
        objects = models.Product.objects.filter(id__in = list(cart.keys()))
        cart_objects = {}
        for id , count in cart.items():
            obj = objects.get(id = id)
            cart_objects[id] = {
                'obj' : obj ,
                'price' : (obj.price - obj.price * obj.discount) * count ,
                'count' : count,
            }
        return render(request , 'core/cart.html' , {'cart': cart_objects ,
                                                                 'total':get_cart_total_price(cart)})

class VerifyView(View):
    pass



class CheckOutView(View):
    def get(self , request ):
        form = forms.InvoiceForm()
        cart = get_cart(request)
        objects = models.Product.objects.filter(id__in = list(cart.keys()))
        cart_objects = {}
        for id , count in cart.items():
            obj = objects.get(id = id)
            cart_objects[id] = {
                'obj' : obj ,
                'price' : (obj.price - obj.price * obj.discount) * count ,
                'count' : count,
            }
        return render(request , 'core/checkout.html' , {'form': form ,'total': get_cart_total_price(cart),
                                                        'cart': cart_objects,})

    def post(self , request ):
        form = forms.InvoiceForm(request.POST)
        if form.is_valid():
            #Create Payment
            invoice = form.save(commit=False)
            invoice.user = request.user
            cart = get_cart(request)
            invoice.total = get_cart_total_price(cart)
            invoice.save()
            items = models.Product.objects.filter(id__in = cart.keys())
            item_objects = []
            for item_id , item_count in cart.items():
                obj = items.get(id=item_id)
                invoice_item_obj = models.InvoiceItem()
                invoice_item_obj.product = obj
                invoice_item_obj.count = item_count
                invoice_item_obj.discount = obj.discount
                invoice_item_obj.price = obj.price
                invoice_item_obj.name = obj.name
                invoice_item_obj.total = invoice_item_obj.total * item_count
                invoice_item_obj.total -= invoice_item_obj.total * invoice_item_obj.discount
                # invoice_item_obj.save()
                item_objects.append(invoice_item_obj)
            models.InvoiceItem.objects.bulk_create(item_objects)
            payment = models.Payment()
            payment.total = invoice.total - invoice.total * invoice.discount
            payment.total += payment.total * invoice.vat
            payment.description = 'kharid az site ma'
            payment.user_ip = get_user_ip(request)


            callback_url = 'http://'+get_current_site(request)+reverse('core:verify')

            res = zarinpal.service.PaymentRequest(mid , payment.total,
                                                  payment.description,
                                                  invoice.user.email ,
                                                  invoice.user.phone,
                                                  callback_url)
            if res.status_code == 100:
                payment.authority = res.Authority
                payment.save()
                return redirect(f'https://sandbox.zarinpal.com/pg/StartPay/{payment.authority}')
            else:
                return render(request , 'core/checkout_error.html' , {'payment': payment})

        return render(request , 'core/checkout.html' , {'form': form })


def get_user_ip(request):
    ip = request.META.get('HTTP_X_FORWARDED_FOR')
    if not ip:
        ip = request.META.get('REMOTE_ADDR')
    return ip




class Test(View):
    def get(self , request):
        if request.headers.get("x-requested-with") == 'XMLHttpRequest':
            a = [
                {'name': 'ali',
                'age' : 20 ,
                }
            ]
        return JsonResponse(a , safe = False)


class AjaxTestPage(View):
    def get(self, request):
        return render(request , 'core/ajaxtest.html')

testing/core/templates/core/ajaxtest.html
{% extends 'base.html' %}

{% block content %}

    <div id="data-container">Nothing yet !</div>
    <a href="#" id="action-link">Do It</a>
    <script type="text/javascript">

        $('add-to-cart-link').click(function (e){

            $.get('{% url 'core:cart_add' %}' , function (res , status , xhr){
                t = JSON.stringify(res);
                $('#data-container').html(t);
            });

           e.preventDefault();
           return false;
        });
    </script>

{% endblock %}

testing/core/templates/core/cart.html
{% extends 'base.html' %}

{% block content %}
    <table>
        <thead>
            <tr>
                <th>Name</th><th>Count</th><th>Discount</th>
                <th>Unit Price</th><th>Price</th>
            </tr>
        </thead>
        <tbody>
            {% for id,item in cart.items %}
            <tr class="item-row" data-id = '{{ id }}'>
                <td>{{ item.obj.name }}</td>
                <td>{{ item.count }}</td>
                <td>{{ item.discount }}</td>
                <td>{{ item.price }}</td>
                <td>{{ item.obj.price }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <br>
    <hr/>
    Total : <span id="total-price">{{ total }}</span>
    <a href="{% url 'core:checkout' %}" class="btn btn-primary">CheckOut</a>
    <script type="text/javascript">

        $('.cart-remove-link').click(function(e){
            target_link = $(this).attr('href');
            link = $(this);
            $.get(target_link , function (res , status , xhr){
                $('#total-price').html(res.total);
                if(!Object.keys(res.cart).includes(link.attr('data-id'))){
                    link.parents('tr').remove();
                }
            });
            e.preventDefault();
            return false;
        });
    </script>

    <a class="btn btn-danger " href="{% url 'core:cart_empty' %}" id="cart-empty-link">delete all</a>

    <script type="text/javascript">
    $('#cart-empty-link').click(function(e){
        e.preventDefault();
        const link = $(this);
        const target_link = link.attr('href');
        $.get(target_link, function(res){
            $('#total-price').html(res.total);
            $('tr.item-row').remove();
        });
        return false;
    });
    </script>

{% endblock %}

testing/core/templates/core/checkout.html
{% extends 'base.html' %}

{% block content %}
        <h1>Invoice</h1>
        <table>
        <thead>
            <tr>
                <th>Name</th><th>Count</th><th>Discount</th>
                <th>Unit Price</th><th>Price</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for id,item in cart.items %}
            <tr class="item-row" data-id = '{{ id }}'>
                <td>{{ item.obj.name }}</td>
                <td>{{ item.count }}</td>
                <td>{{ item.discount }}</td>
                <td>{{ item.price }}</td>
                <td>{{ item.obj.price }}</td>
                <td><a class="btn btn-secondary cart-remove-link" href="{% url 'core:cart_remove' id=id %}" data-id="{{ id }}">X</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <br>
    <hr/>
    Total : <span id="total-price">{{ total }}</span>


    <form method="post" action={% url 'core:checkout' %}>
    {% csrf_token %}
        <table>
        {{ form }}
    </table>
    <input type="submit" class="btn btn-primary" value="Pay"/>

    </form>

{% endblock %}

testing/core/templates/core/product_list.html
{% extends "base.html" %}


{% block content %}
     Total Products : {{ products|length }}
    {% for product in products %}

                    <div class="col">
                        <div class="card shadow-sm">
                            {% if product.image %}
                                <img class="bd-placeholder-img card-img-top" src="{{ product.image.url }}" alt="{{ product.name }}">
                            {% else %}
                                <svg class="bd-placeholder-img card- img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false">
                                    <title>Placeholder</title>
                                    <rect width="100%" height="100%" fill="#55595c"></rect>
                                    <text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text>
                                </svg>
                            {% endif %}
                            <div class="card-body">
                                <p class="card-text">
                                    <b>{{ product.name }}</b><br/>
                                    <b>Price: </b>{{ product.price }}<br/>
                                    <br>
                                    {{ product.description }}
                                </p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">

                                        <button type="button" class="btn btn-sm btn-outline-secondary">Details</button>
                                        <a href="{% url 'core:cart_add' product.id %}" data-id="{{ product.id }}" class="btn btn-sm btn-outline-secondary add-to-cart-link">Add To Cart</a>
                                    </div>
                                    <small class="text-body-secondary">{{ product.discount }}%</small>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    <script type="text/javascript">

                    $('add-to-cart-link').click(function (e){
                        target_link = $(this).attr('href');
                        $.get(target_link , function (res , status , xhr){
                            console.log(res);
                            item_count = object.keys(res).length;
                            $('#cart-count').html(item_count);
                        });
                       e.preventDefault();
                       return false;
                    });
                </script>
{% endblock %}